Rafaela Ayumi Uehara

In [1]:
import numpy as np
import pandas as pd

# Definindo uma semente para garantir que os dados sejam reprodutíveis
np.random.seed(42)

# Criando um dataset fictício de 30 linhas (30 funcionários) com as colunas ID, Idade, Salário, Anos de Experiência
n = 30
ids = np.arange(1, n + 1)  # IDs de 1 a 30
idades = np.random.randint(20, 60, size=n)  # Idades entre 20 e 60 anos
salarios = np.random.randint(40000, 100000, size=n)  # Salários entre 40.000 e 100.000
anos_experiencia = np.random.randint(1, 35, size=n)  # Anos de experiência entre 1 e 35 anos

# Combinando os dados em um array
dataset = np.column_stack((ids, idades, salarios, anos_experiencia))

# Convertendo para DataFrame para visualização
df = pd.DataFrame(dataset, columns=['ID', 'Idade', 'Salário', 'Anos de Experiência'])

# Exibindo o DataFrame
# print(df)

#Transformar em array
a=np.array(df)
print(a)

[[    1    58 40189     7]
 [    2    48 59118     8]
 [    3    34 75773    14]
 [    4    27 93810    17]
 [    5    40 41899     4]
 [    6    58 96886     2]
 [    7    38 41267     6]
 [    8    42 71551     4]
 [    9    30 90680    29]
 [   10    30 51394    18]
 [   11    43 43556    26]
 [   12    55 43890    34]
 [   13    59 81606    10]
 [   14    43 70740    14]
 [   15    22 54502    31]
 [   16    41 61777    15]
 [   17    21 50627     8]
 [   18    43 48792    14]
 [   19    49 83323    23]
 [   20    57 83021    21]
 [   21    21 48433    16]
 [   22    40 83001    18]
 [   23    52 51016    24]
 [   24    31 63897    26]
 [   25    41 42612    25]
 [   26    44 96193    29]
 [   27    46 98707    15]
 [   28    47 95387     1]
 [   29    35 94638    25]
 [   30    34 63483     7]]


Redimensionar o dataset (por exemplo, transformar 30 linhas em 10 linhas e 12 colunas)

In [2]:
aRedimensionado = np.resize (a,(10,12))
print (aRedimensionado)

[[    1    58 40189     7     2    48 59118     8     3    34 75773    14]
 [    4    27 93810    17     5    40 41899     4     6    58 96886     2]
 [    7    38 41267     6     8    42 71551     4     9    30 90680    29]
 [   10    30 51394    18    11    43 43556    26    12    55 43890    34]
 [   13    59 81606    10    14    43 70740    14    15    22 54502    31]
 [   16    41 61777    15    17    21 50627     8    18    43 48792    14]
 [   19    49 83323    23    20    57 83021    21    21    21 48433    16]
 [   22    40 83001    18    23    52 51016    24    24    31 63897    26]
 [   25    41 42612    25    26    44 96193    29    27    46 98707    15]
 [   28    47 95387     1    29    35 94638    25    30    34 63483     7]]


Acessar o primeiro elemento (primeira linha) do dataset

In [3]:
aPrimeiro = a[0]
print (aPrimeiro)

[    1    58 40189     7]


Acessar o salário (terceira coluna) da terceira pessoa

In [4]:
aSalarioTerceiro = a[2,2]
print (aSalarioTerceiro)

75773


Selecionar os salários de todos os funcionários

In [5]:
aSalario = a[:,2]
print (aSalario)

[40189 59118 75773 93810 41899 96886 41267 71551 90680 51394 43556 43890
 81606 70740 54502 61777 50627 48792 83323 83021 48433 83001 51016 63897
 42612 96193 98707 95387 94638 63483]


Concatenar o dataset com um array de bônus (por exemplo, uma nova coluna)

In [6]:
b = [(a[i]-2) for i in range(len(a))]
ab = np.concatenate((a,b))
print (ab)

[[    1    58 40189     7]
 [    2    48 59118     8]
 [    3    34 75773    14]
 [    4    27 93810    17]
 [    5    40 41899     4]
 [    6    58 96886     2]
 [    7    38 41267     6]
 [    8    42 71551     4]
 [    9    30 90680    29]
 [   10    30 51394    18]
 [   11    43 43556    26]
 [   12    55 43890    34]
 [   13    59 81606    10]
 [   14    43 70740    14]
 [   15    22 54502    31]
 [   16    41 61777    15]
 [   17    21 50627     8]
 [   18    43 48792    14]
 [   19    49 83323    23]
 [   20    57 83021    21]
 [   21    21 48433    16]
 [   22    40 83001    18]
 [   23    52 51016    24]
 [   24    31 63897    26]
 [   25    41 42612    25]
 [   26    44 96193    29]
 [   27    46 98707    15]
 [   28    47 95387     1]
 [   29    35 94638    25]
 [   30    34 63483     7]
 [   -1    56 40187     5]
 [    0    46 59116     6]
 [    1    32 75771    12]
 [    2    25 93808    15]
 [    3    38 41897     2]
 [    4    56 96884     0]
 [    5    36 41265     4]
 

Transpor o dataset

In [7]:
aTransposta = a.T
print (aTransposta)

[[    1     2     3     4     5     6     7     8     9    10    11    12
     13    14    15    16    17    18    19    20    21    22    23    24
     25    26    27    28    29    30]
 [   58    48    34    27    40    58    38    42    30    30    43    55
     59    43    22    41    21    43    49    57    21    40    52    31
     41    44    46    47    35    34]
 [40189 59118 75773 93810 41899 96886 41267 71551 90680 51394 43556 43890
  81606 70740 54502 61777 50627 48792 83323 83021 48433 83001 51016 63897
  42612 96193 98707 95387 94638 63483]
 [    7     8    14    17     4     2     6     4    29    18    26    34
     10    14    31    15     8    14    23    21    16    18    24    26
     25    29    15     1    25     7]]


Calcular a soma dos salários

In [8]:
somaSalarios = a[:,2].sum()
print (somaSalarios)

2021768


Calcular a média dos anos de experiência

In [9]:
mediaExp = (a[:,3].sum())/30
print (mediaExp)

16.366666666666667


Calcular o desvio padrão das idades

In [10]:
desvioPadrao = np.std (a[:,1])
print(desvioPadrao)

10.824303929378349


Multiplicar o salário e os anos de experiência de cada funcionário

In [11]:
salExp = [(a[i,2]*a[i,3]) for i in range(len(a))]
print (salExp)

[281323, 472944, 1060822, 1594770, 167596, 193772, 247602, 286204, 2629720, 925092, 1132456, 1492260, 816060, 990360, 1689562, 926655, 405016, 683088, 1916429, 1743441, 774928, 1494018, 1224384, 1661322, 1065300, 2789597, 1480605, 95387, 2365950, 444381]


Calcular o produto da matriz transposta do dataset com ela mesma

In [12]:
transProd = np.matmul (a,aTransposta)
print (transProd)

[[ 1615159135 -1919071152 -1249724126  -524835517  1683881264  -401212458
   1658481716 -1419401685  -650626824  2065475342  1750474771  1763898650
  -1015300257 -1451994830 -2104584910 -1812208944  2034649794  1960904298
   -946296227  -958432854  1946475188  -959237639  2050285231 -1727008759
   1712536246  -429064038  -328028873  -461456392  -491558480 -1743646958]
 [-1919071152  -800027000   184582668  1250893724 -1817980252  1432742064
  -1855342904   -65013214  1065854634 -1256655200 -1720021394 -1700275340
    529419150  -112957772 -1072916726  -642832490 -1301999204 -1410479628
    630924392   613071126 -1431704024   611887930 -1279000674  -517502706
  -1775828862  1391772874  1540395512  1344123690  1299843926  -541977554]
 [-1249724126   184582668  1446581594 -1481668294 -1120152938 -1248589696
  -1168041508  1126668135 -1718837499  -400688432  -994596649  -969287944
   1888566327  1065216424  -165186023   386062977  -458806748  -597849368
   2018668428  1995785229  -62505258

Filtrar funcionários com salários maiores que 60.000

In [13]:
func60mais = np.extract(a[:,2]>=60000, a)
print (func60mais)

[40189     7    48     8     3     4    27    17 41899     4    58     2
    38 41267     6     8    42]


Ordenar o dataset pelo salário

In [14]:
aOrdenadoSal = a[a[:,2].argsort()]
print (aOrdenadoSal)

[[    1    58 40189     7]
 [    7    38 41267     6]
 [    5    40 41899     4]
 [   25    41 42612    25]
 [   11    43 43556    26]
 [   12    55 43890    34]
 [   21    21 48433    16]
 [   18    43 48792    14]
 [   17    21 50627     8]
 [   23    52 51016    24]
 [   10    30 51394    18]
 [   15    22 54502    31]
 [    2    48 59118     8]
 [   16    41 61777    15]
 [   30    34 63483     7]
 [   24    31 63897    26]
 [   14    43 70740    14]
 [    8    42 71551     4]
 [    3    34 75773    14]
 [   13    59 81606    10]
 [   22    40 83001    18]
 [   20    57 83021    21]
 [   19    49 83323    23]
 [    9    30 90680    29]
 [    4    27 93810    17]
 [   29    35 94638    25]
 [   28    47 95387     1]
 [   26    44 96193    29]
 [    6    58 96886     2]
 [   27    46 98707    15]]


Criar uma cópia do dataset

In [15]:
aCopy = a.copy()
print (aCopy)

[[    1    58 40189     7]
 [    2    48 59118     8]
 [    3    34 75773    14]
 [    4    27 93810    17]
 [    5    40 41899     4]
 [    6    58 96886     2]
 [    7    38 41267     6]
 [    8    42 71551     4]
 [    9    30 90680    29]
 [   10    30 51394    18]
 [   11    43 43556    26]
 [   12    55 43890    34]
 [   13    59 81606    10]
 [   14    43 70740    14]
 [   15    22 54502    31]
 [   16    41 61777    15]
 [   17    21 50627     8]
 [   18    43 48792    14]
 [   19    49 83323    23]
 [   20    57 83021    21]
 [   21    21 48433    16]
 [   22    40 83001    18]
 [   23    52 51016    24]
 [   24    31 63897    26]
 [   25    41 42612    25]
 [   26    44 96193    29]
 [   27    46 98707    15]
 [   28    47 95387     1]
 [   29    35 94638    25]
 [   30    34 63483     7]]
