## Exercícios Numpy e Python

In [69]:
import numpy 

##### Criando um dataframe fictício

In [9]:
import pandas as pd

# Definindo uma semente para garantir que os dados sejam reprodutíveis
np.random.seed(42)

# Criando um dataset fictício de 30 linhas (30 funcionários) com as colunas ID, Idade, Salário, Anos de Experiência
n = 30
ids = np.arange(1, n + 1)  # IDs de 1 a 30
idades = np.random.randint(20, 60, size=n)  # Idades entre 20 e 60 anos
salarios = np.random.randint(40000, 100000, size=n)  # Salários entre 40.000 e 100.000
anos_experiencia = np.random.randint(1, 35, size=n)  # Anos de experiência entre 1 e 35 anos

# Combinando os dados em um array
dataset = np.column_stack((ids, idades, salarios, anos_experiencia))

# Convertendo para DataFrame para visualização
df = pd.DataFrame(dataset, columns=['ID', 'Idade', 'Salário', 'Anos de Experiência'])

In [11]:
df

ID  Idade  Salário  Anos de Experiência
0    1     58    40189                    7
1    2     48    59118                    8
2    3     34    75773                   14
3    4     27    93810                   17
4    5     40    41899                    4
5    6     58    96886                    2
6    7     38    41267                    6
7    8     42    71551                    4
8    9     30    90680                   29
9   10     30    51394                   18
10  11     43    43556                   26
11  12     55    43890                   34
12  13     59    81606                   10
13  14     43    70740                   14
14  15     22    54502                   31
15  16     41    61777                   15
16  17     21    50627                    8
17  18     43    48792                   14
18  19     49    83323                   23
19  20     57    83021                   21
20  21     21    48433                   16
21  22     40    83001                   18
22  23     52    51016                   24
23  24     31    63897                   26
24  25     41    42612                   25
25  26     44    96193                   29
26  27     46    98707                   15
27  28     47    95387                    1
28  29     35    94638                   25
29  30     34    63483                    7

1. Redimensionar o dataset (por exemplo, transformar 30 linhas em 10 linhas e 12 colunas)


In [41]:
#transformando o dataframe e array
df_array = df.values
redimensionado = df_array.reshape(60,2) #60 linhas e 2 colunas
redimensionado2 = df_array.reshape(10,12) #10 linhas e 12 colunas

2. Acessar o primeiro elemento (primeira linha) do dataset

In [44]:
df_array[0]

array([    1,    58, 40189,     7])

3. Acessar o salário (terceira coluna) da terceira pessoa

In [63]:
df_array[2][2]

75773

4. Selecionar os salários de todos os funcionários

In [58]:
df_array[:,2]

array([40189, 59118, 75773, 93810, 41899, 96886, 41267, 71551, 90680,
       51394, 43556, 43890, 81606, 70740, 54502, 61777, 50627, 48792,
       83323, 83021, 48433, 83001, 51016, 63897, 42612, 96193, 98707,
       95387, 94638, 63483])

5. Concatenar o dataset com um array de bônus (por exemplo, uma nova coluna)


In [97]:
rng = np.random.default_rng()
nova = rng.random((30,1))

concatenado = np.concatenate((df_array, nova), axis = 1)
concatenado

array([[    1.  ,    58.  , 40189.  ,     7.  ,     0.55],
       [    2.  ,    48.  , 59118.  ,     8.  ,     0.12],
       [    3.  ,    34.  , 75773.  ,    14.  ,     0.09],
       [    4.  ,    27.  , 93810.  ,    17.  ,     0.36],
       [    5.  ,    40.  , 41899.  ,     4.  ,     0.63],
       [    6.  ,    58.  , 96886.  ,     2.  ,     0.69],
       [    7.  ,    38.  , 41267.  ,     6.  ,     0.29],
       [    8.  ,    42.  , 71551.  ,     4.  ,     0.07],
       [    9.  ,    30.  , 90680.  ,    29.  ,     0.95],
       [   10.  ,    30.  , 51394.  ,    18.  ,     0.81],
       [   11.  ,    43.  , 43556.  ,    26.  ,     0.34],
       [   12.  ,    55.  , 43890.  ,    34.  ,     0.36],
       [   13.  ,    59.  , 81606.  ,    10.  ,     0.97],
       [   14.  ,    43.  , 70740.  ,    14.  ,     0.81],
       [   15.  ,    22.  , 54502.  ,    31.  ,     0.84],
       [   16.  ,    41.  , 61777.  ,    15.  ,     0.38],
       [   17.  ,    21.  , 50627.  ,     8.  ,     0.06

6. Transpor o dataset


In [102]:
transposta = df_array.T
transposta

array([[    1,     2,     3,     4,     5,     6,     7,     8,     9,
           10,    11,    12,    13,    14,    15,    16,    17,    18,
           19,    20,    21,    22,    23,    24,    25,    26,    27,
           28,    29,    30],
       [   58,    48,    34,    27,    40,    58,    38,    42,    30,
           30,    43,    55,    59,    43,    22,    41,    21,    43,
           49,    57,    21,    40,    52,    31,    41,    44,    46,
           47,    35,    34],
       [40189, 59118, 75773, 93810, 41899, 96886, 41267, 71551, 90680,
        51394, 43556, 43890, 81606, 70740, 54502, 61777, 50627, 48792,
        83323, 83021, 48433, 83001, 51016, 63897, 42612, 96193, 98707,
        95387, 94638, 63483],
       [    7,     8,    14,    17,     4,     2,     6,     4,    29,
           18,    26,    34,    10,    14,    31,    15,     8,    14,
           23,    21,    16,    18,    24,    26,    25,    29,    15,
            1,    25,     7]])

7. Calcular a soma dos salários

In [105]:
soma = np.sum(df_array[:,2])
soma

2021768

8. Calcular a média dos anos de experiência


In [110]:
media = np.mean(df_array[:,3])
media

16.366666666666667

9. Calcular o desvio padrão das idades


In [113]:
desvio = np.std(df_array[:,1])
desvio

10.824303929378349

10. Multiplicar o salário e os anos de experiência de cada funcionário


In [118]:
multiplicação = df_array[:,2]*df_array[:,3]
multiplicação

array([ 281323,  472944, 1060822, 1594770,  167596,  193772,  247602,
        286204, 2629720,  925092, 1132456, 1492260,  816060,  990360,
       1689562,  926655,  405016,  683088, 1916429, 1743441,  774928,
       1494018, 1224384, 1661322, 1065300, 2789597, 1480605,   95387,
       2365950,  444381])

11. Calcular o produto da matriz transposta do dataset com ela mesma


In [123]:
produto = df_array@transposta
produto

#ou

array([[        9455,        18797,     32689846,         8305],
       [       18797,        53863,     83705033,        19639],
       [    32689846,     83705033, 148351518064,     33051044],
       [        8305,        19639,     33051044,        10577]])

In [125]:
produto2 = np.dot(transposta, df_array)
produto2

array([[        9455,        18797,     32689846,         8305],
       [       18797,        53863,     83705033,        19639],
       [    32689846,     83705033, 148351518064,     33051044],
       [        8305,        19639,     33051044,        10577]])

12. Filtrar funcionários com salários maiores que 60.000


In [140]:
filtro = df_array[df_array[:,2]>60000]
filtro

array([[    3,    34, 75773,    14],
       [    4,    27, 93810,    17],
       [    6,    58, 96886,     2],
       [    8,    42, 71551,     4],
       [    9,    30, 90680,    29],
       [   13,    59, 81606,    10],
       [   14,    43, 70740,    14],
       [   16,    41, 61777,    15],
       [   19,    49, 83323,    23],
       [   20,    57, 83021,    21],
       [   22,    40, 83001,    18],
       [   24,    31, 63897,    26],
       [   26,    44, 96193,    29],
       [   27,    46, 98707,    15],
       [   28,    47, 95387,     1],
       [   29,    35, 94638,    25],
       [   30,    34, 63483,     7]])

13. Ordenar o dataset pelo salário


In [147]:
ordenado = df_array[np.argsort(df_array[:, 2])[::-1]]
ordenado

array([[   27,    46, 98707,    15],
       [    6,    58, 96886,     2],
       [   26,    44, 96193,    29],
       [   28,    47, 95387,     1],
       [   29,    35, 94638,    25],
       [    4,    27, 93810,    17],
       [    9,    30, 90680,    29],
       [   19,    49, 83323,    23],
       [   20,    57, 83021,    21],
       [   22,    40, 83001,    18],
       [   13,    59, 81606,    10],
       [    3,    34, 75773,    14],
       [    8,    42, 71551,     4],
       [   14,    43, 70740,    14],
       [   24,    31, 63897,    26],
       [   30,    34, 63483,     7],
       [   16,    41, 61777,    15],
       [    2,    48, 59118,     8],
       [   15,    22, 54502,    31],
       [   10,    30, 51394,    18],
       [   23,    52, 51016,    24],
       [   17,    21, 50627,     8],
       [   18,    43, 48792,    14],
       [   21,    21, 48433,    16],
       [   12,    55, 43890,    34],
       [   11,    43, 43556,    26],
       [   25,    41, 42612,    25],
 

14. Criar uma cópia do dataset


In [150]:
copia = df_array.copy()
novodf = pd.DataFrame(copia)
novodf

0   1      2   3
0    1  58  40189   7
1    2  48  59118   8
2    3  34  75773  14
3    4  27  93810  17
4    5  40  41899   4
5    6  58  96886   2
6    7  38  41267   6
7    8  42  71551   4
8    9  30  90680  29
9   10  30  51394  18
10  11  43  43556  26
11  12  55  43890  34
12  13  59  81606  10
13  14  43  70740  14
14  15  22  54502  31
15  16  41  61777  15
16  17  21  50627   8
17  18  43  48792  14
18  19  49  83323  23
19  20  57  83021  21
20  21  21  48433  16
21  22  40  83001  18
22  23  52  51016  24
23  24  31  63897  26
24  25  41  42612  25
25  26  44  96193  29
26  27  46  98707  15
27  28  47  95387   1
28  29  35  94638  25
29  30  34  63483   7