# Exercícios NUMPY - Aula 5

In [6]:
import numpy as np
import pandas as pd

# Definindo uma semente para garantir que os dados sejam reprodutíveis
np.random.seed(42)

# Criando um dataset fictício de 30 linhas (30 funcionários) com as colunas ID, Idade, Salário, Anos de Experiência
n = 30
ids = np.arange(1, n + 1)  # IDs de 1 a 30
idades = np.random.randint(20, 60, size=n)  # Idades entre 20 e 60 anos
salarios = np.random.randint(40000, 100000, size=n)  # Salários entre 40.000 e 100.000
anos_experiencia = np.random.randint(1, 35, size=n)  # Anos de experiência entre 1 e 35 anos

# Combinando os dados em um array
dataset = np.column_stack((ids, idades, salarios, anos_experiencia))

# Convertendo para DataFrame para visualização
df = pd.DataFrame(dataset, columns=['ID', 'Idade', 'Salário', 'Anos de Experiência'])

# Exibindo o DataFrame
# print(df)

### 1. Redimensionar o dataset (transformar 30 linhas em 10 linhas e 12 colunas)

In [7]:
dataset_redimensionado = dataset.reshape(10, 12)
print("Dataset redimensionado (10x12):")
print(dataset_redimensionado)

Dataset redimensionado (10x12):
[[    1    58 40189     7     2    48 59118     8     3    34 75773    14]
 [    4    27 93810    17     5    40 41899     4     6    58 96886     2]
 [    7    38 41267     6     8    42 71551     4     9    30 90680    29]
 [   10    30 51394    18    11    43 43556    26    12    55 43890    34]
 [   13    59 81606    10    14    43 70740    14    15    22 54502    31]
 [   16    41 61777    15    17    21 50627     8    18    43 48792    14]
 [   19    49 83323    23    20    57 83021    21    21    21 48433    16]
 [   22    40 83001    18    23    52 51016    24    24    31 63897    26]
 [   25    41 42612    25    26    44 96193    29    27    46 98707    15]
 [   28    47 95387     1    29    35 94638    25    30    34 63483     7]]


### 2. Acessar o primeiro elemento (primeira linha) do dataset

In [8]:
primeira_linha = dataset[0]
print("Primeira linha do dataset:")
print(primeira_linha)

Primeira linha do dataset:
[    1    58 40189     7]


### 3. Acessar o salário (terceira coluna) da terceira pessoa

In [9]:
salario_terceira_pessoa = dataset[2, 2]
print(f"Salário da terceira pessoa: {salario_terceira_pessoa}")

Salário da terceira pessoa: 75773


### 4. Selecionar os salários de todos os funcionários

In [10]:
todos_salarios = dataset[:, 2]
print("Salários de todos os funcionários:")
print(todos_salarios)

Salários de todos os funcionários:
[40189 59118 75773 93810 41899 96886 41267 71551 90680 51394 43556 43890
 81606 70740 54502 61777 50627 48792 83323 83021 48433 83001 51016 63897
 42612 96193 98707 95387 94638 63483]


### 5. Concatenar o dataset com um array de bônus (nova coluna)

In [11]:
bonus = np.random.randint(5000, 15000, size=n).reshape(n, 1)
dataset_com_bonus = np.hstack((dataset, bonus))
print("Dataset com coluna de bônus:")
print(dataset_com_bonus)

Dataset com coluna de bônus:
[[    1    58 40189     7  7568]
 [    2    48 59118     8 10463]
 [    3    34 75773    14  7027]
 [    4    27 93810    17  7695]
 [    5    40 41899     4 14687]
 [    6    58 96886     2 10258]
 [    7    38 41267     6 10618]
 [    8    42 71551     4 11736]
 [    9    30 90680    29  5391]
 [   10    30 51394    18 10892]
 [   11    43 43556    26  8561]
 [   12    55 43890    34 11184]
 [   13    59 81606    10  8099]
 [   14    43 70740    14 11278]
 [   15    22 54502    31 13392]
 [   16    41 61777    15  8104]
 [   17    21 50627     8 12215]
 [   18    43 48792    14  7454]
 [   19    49 83323    23 13996]
 [   20    57 83021    21  7731]
 [   21    21 48433    16 13154]
 [   22    40 83001    18 14762]
 [   23    52 51016    24 10056]
 [   24    31 63897    26 13110]
 [   25    41 42612    25  8840]
 [   26    44 96193    29  6028]
 [   27    46 98707    15 12385]
 [   28    47 95387     1  5502]
 [   29    35 94638    25 11910]
 [   30    34 

### 6. Transpor o dataset

In [12]:
dataset_transposto = dataset.T
print("Dataset transposto:")
print(dataset_transposto)

Dataset transposto:
[[    1     2     3     4     5     6     7     8     9    10    11    12
     13    14    15    16    17    18    19    20    21    22    23    24
     25    26    27    28    29    30]
 [   58    48    34    27    40    58    38    42    30    30    43    55
     59    43    22    41    21    43    49    57    21    40    52    31
     41    44    46    47    35    34]
 [40189 59118 75773 93810 41899 96886 41267 71551 90680 51394 43556 43890
  81606 70740 54502 61777 50627 48792 83323 83021 48433 83001 51016 63897
  42612 96193 98707 95387 94638 63483]
 [    7     8    14    17     4     2     6     4    29    18    26    34
     10    14    31    15     8    14    23    21    16    18    24    26
     25    29    15     1    25     7]]


### 7. Calcular a soma dos salários

In [13]:
soma_salarios = np.sum(dataset[:, 2])
print(f"Soma dos salários: {soma_salarios}")

Soma dos salários: 2021768


### 8. Calcular a média dos anos de experiência

In [14]:
media_experiencia = np.mean(dataset[:, 3])
print(f"Média dos anos de experiência: {media_experiencia}")

Média dos anos de experiência: 16.366666666666667


### 9. Calcular o desvio padrão das idades

In [15]:
desvio_padrao_idades = np.std(dataset[:, 1])
print(f"Desvio padrão das idades: {desvio_padrao_idades}")

Desvio padrão das idades: 10.824303929378349


### 10. Multiplicar o salário e os anos de experiência de cada funcionário

In [16]:
salario_experiencia = dataset[:, 2] * dataset[:, 3]
print("Produto do salário e anos de experiência de cada funcionário:")
print(salario_experiencia)

Produto do salário e anos de experiência de cada funcionário:
[ 281323  472944 1060822 1594770  167596  193772  247602  286204 2629720
  925092 1132456 1492260  816060  990360 1689562  926655  405016  683088
 1916429 1743441  774928 1494018 1224384 1661322 1065300 2789597 1480605
   95387 2365950  444381]


### 11. Calcular o produto da matriz transposta do dataset com ela mesma

In [17]:
produto_matriz = np.dot(dataset.T, dataset)
print("Produto da matriz transposta com ela mesma:")
print(produto_matriz)

Produto da matriz transposta com ela mesma:
[[        9455        18797     32689846         8305]
 [       18797        53863     83705033        19639]
 [    32689846     83705033 148351518064     33051044]
 [        8305        19639     33051044        10577]]


### 12. Filtrar funcionários com salários maiores que 60.000

In [18]:
salarios_acima_60k = dataset[dataset[:, 2] > 60000]
print("Funcionários com salários acima de 60.000:")
print(salarios_acima_60k)

Funcionários com salários acima de 60.000:
[[    3    34 75773    14]
 [    4    27 93810    17]
 [    6    58 96886     2]
 [    8    42 71551     4]
 [    9    30 90680    29]
 [   13    59 81606    10]
 [   14    43 70740    14]
 [   16    41 61777    15]
 [   19    49 83323    23]
 [   20    57 83021    21]
 [   22    40 83001    18]
 [   24    31 63897    26]
 [   26    44 96193    29]
 [   27    46 98707    15]
 [   28    47 95387     1]
 [   29    35 94638    25]
 [   30    34 63483     7]]


### 13. Ordenar o dataset pelo salário

In [19]:
dataset_ordenado = dataset[dataset[:, 2].argsort()]
print("Dataset ordenado pelo salário:")
print(dataset_ordenado)

Dataset ordenado pelo salário:
[[    1    58 40189     7]
 [    7    38 41267     6]
 [    5    40 41899     4]
 [   25    41 42612    25]
 [   11    43 43556    26]
 [   12    55 43890    34]
 [   21    21 48433    16]
 [   18    43 48792    14]
 [   17    21 50627     8]
 [   23    52 51016    24]
 [   10    30 51394    18]
 [   15    22 54502    31]
 [    2    48 59118     8]
 [   16    41 61777    15]
 [   30    34 63483     7]
 [   24    31 63897    26]
 [   14    43 70740    14]
 [    8    42 71551     4]
 [    3    34 75773    14]
 [   13    59 81606    10]
 [   22    40 83001    18]
 [   20    57 83021    21]
 [   19    49 83323    23]
 [    9    30 90680    29]
 [    4    27 93810    17]
 [   29    35 94638    25]
 [   28    47 95387     1]
 [   26    44 96193    29]
 [    6    58 96886     2]
 [   27    46 98707    15]]


### 14. Criar uma cópia do dataset

In [20]:
dataset_copia = dataset.copy()
print("Cópia do dataset:")
print(dataset_copia)

Cópia do dataset:
[[    1    58 40189     7]
 [    2    48 59118     8]
 [    3    34 75773    14]
 [    4    27 93810    17]
 [    5    40 41899     4]
 [    6    58 96886     2]
 [    7    38 41267     6]
 [    8    42 71551     4]
 [    9    30 90680    29]
 [   10    30 51394    18]
 [   11    43 43556    26]
 [   12    55 43890    34]
 [   13    59 81606    10]
 [   14    43 70740    14]
 [   15    22 54502    31]
 [   16    41 61777    15]
 [   17    21 50627     8]
 [   18    43 48792    14]
 [   19    49 83323    23]
 [   20    57 83021    21]
 [   21    21 48433    16]
 [   22    40 83001    18]
 [   23    52 51016    24]
 [   24    31 63897    26]
 [   25    41 42612    25]
 [   26    44 96193    29]
 [   27    46 98707    15]
 [   28    47 95387     1]
 [   29    35 94638    25]
 [   30    34 63483     7]]
