# Atividade Numpy

## Exercícios

Vamos criar um dataset para aplicarmos alguns comandos do python e numpy.


In [45]:
import numpy as np
import pandas as pd

# Definindo uma semente para garantir que os dados sejam reprodutíveis
np.random.seed(42)

# Criando um dataset fictício de 30 linhas (30 funcionários) com as colunas ID, Idade, Salário, Anos de Experiência
n = 30
ids = np.arange(1, n + 1)  # IDs de 1 a 30
idades = np.random.randint(20, 60, size=n)  # Idades entre 20 e 60 anos
salarios = np.random.randint(40000, 100000, size=n)  # Salários entre 40.000 e 100.000
anos_experiencia = np.random.randint(1, 35, size=n)  # Anos de experiência entre 1 e 35 anos

# Combinando os dados em um array
dataset = np.column_stack((ids, idades, salarios, anos_experiencia))

# Convertendo para DataFrame para visualização
df = pd.DataFrame(dataset, columns=['ID', 'Idade', 'Salário', 'Anos de Experiência'])

# Exibindo o DataFrame
print(df)

    ID  Idade  Salário  Anos de Experiência
0    1     58    40189                    7
1    2     48    59118                    8
2    3     34    75773                   14
3    4     27    93810                   17
4    5     40    41899                    4
5    6     58    96886                    2
6    7     38    41267                    6
7    8     42    71551                    4
8    9     30    90680                   29
9   10     30    51394                   18
10  11     43    43556                   26
11  12     55    43890                   34
12  13     59    81606                   10
13  14     43    70740                   14
14  15     22    54502                   31
15  16     41    61777                   15
16  17     21    50627                    8
17  18     43    48792                   14
18  19     49    83323                   23
19  20     57    83021                   21
20  21     21    48433                   16
21  22     40    83001          

 - Redimensionar o dataset (por exemplo, transformar 30 linhas em 10 linhas e 12 colunas)

In [46]:
reshape = dataset.reshape(10, 12)
print(reshape)

[[    1    58 40189     7     2    48 59118     8     3    34 75773    14]
 [    4    27 93810    17     5    40 41899     4     6    58 96886     2]
 [    7    38 41267     6     8    42 71551     4     9    30 90680    29]
 [   10    30 51394    18    11    43 43556    26    12    55 43890    34]
 [   13    59 81606    10    14    43 70740    14    15    22 54502    31]
 [   16    41 61777    15    17    21 50627     8    18    43 48792    14]
 [   19    49 83323    23    20    57 83021    21    21    21 48433    16]
 [   22    40 83001    18    23    52 51016    24    24    31 63897    26]
 [   25    41 42612    25    26    44 96193    29    27    46 98707    15]
 [   28    47 95387     1    29    35 94638    25    30    34 63483     7]]


 - Acessar o primeiro elemento (primeira linha) do dataset


In [47]:
first_line = dataset[0,:]
print(first_line)

[    1    58 40189     7]


 - Acessar o salário (terceira coluna) da terceira pessoa


In [48]:
third_person_salary = dataset[2,2]
print(third_person_salary)

75773


 - Selecionar os salários de todos os funcionários


In [49]:
salaries = dataset[:,2]
print(salaries)

[40189 59118 75773 93810 41899 96886 41267 71551 90680 51394 43556 43890
 81606 70740 54502 61777 50627 48792 83323 83021 48433 83001 51016 63897
 42612 96193 98707 95387 94638 63483]


 - Concatenar o dataset com um array de bônus (por exemplo, uma nova coluna)


In [50]:
np.random.seed(42)
n = 30
bonus = np.random.randint(0, 1000, size=n)
bonus_dataset = np.column_stack((dataset, bonus))
print(bonus_dataset)

[[    1    58 40189     7   102]
 [    2    48 59118     8   435]
 [    3    34 75773    14   860]
 [    4    27 93810    17   270]
 [    5    40 41899     4   106]
 [    6    58 96886     2    71]
 [    7    38 41267     6   700]
 [    8    42 71551     4    20]
 [    9    30 90680    29   614]
 [   10    30 51394    18   121]
 [   11    43 43556    26   466]
 [   12    55 43890    34   214]
 [   13    59 81606    10   330]
 [   14    43 70740    14   458]
 [   15    22 54502    31    87]
 [   16    41 61777    15   372]
 [   17    21 50627     8    99]
 [   18    43 48792    14   871]
 [   19    49 83323    23   663]
 [   20    57 83021    21   130]
 [   21    21 48433    16   661]
 [   22    40 83001    18   308]
 [   23    52 51016    24   769]
 [   24    31 63897    26   343]
 [   25    41 42612    25   491]
 [   26    44 96193    29   413]
 [   27    46 98707    15   805]
 [   28    47 95387     1   385]
 [   29    35 94638    25   191]
 [   30    34 63483     7   955]]


 - Transpor o dataset


In [51]:
transposed = dataset.T
print(transposed)

[[    1     2     3     4     5     6     7     8     9    10    11    12
     13    14    15    16    17    18    19    20    21    22    23    24
     25    26    27    28    29    30]
 [   58    48    34    27    40    58    38    42    30    30    43    55
     59    43    22    41    21    43    49    57    21    40    52    31
     41    44    46    47    35    34]
 [40189 59118 75773 93810 41899 96886 41267 71551 90680 51394 43556 43890
  81606 70740 54502 61777 50627 48792 83323 83021 48433 83001 51016 63897
  42612 96193 98707 95387 94638 63483]
 [    7     8    14    17     4     2     6     4    29    18    26    34
     10    14    31    15     8    14    23    21    16    18    24    26
     25    29    15     1    25     7]]


 - Calcular a soma dos salários


In [52]:
salaries_sum = dataset[:,2].sum()
print(salaries_sum)

2021768


 - Calcular a média dos anos de experiência


In [53]:
experience_mean = dataset[:,3].mean()
print(experience_mean)

16.366666666666667


 - Calcular o desvio padrão das idades


In [54]:
age_std = dataset[:,1].std()
print(age_std)

10.824303929378349


 - Multiplicar o salário e os anos de experiência de cada funcionário


In [55]:
product = dataset[:,2] * dataset[:,3]
print(product)

[ 281323  472944 1060822 1594770  167596  193772  247602  286204 2629720
  925092 1132456 1492260  816060  990360 1689562  926655  405016  683088
 1916429 1743441  774928 1494018 1224384 1661322 1065300 2789597 1480605
   95387 2365950  444381]


 - Calcular o produto da matriz transposta do dataset com ela mesma


In [56]:
transposed = dataset.T
transposed_product = transposed * transposed
print(transposed_product)

[[         1          4          9         16         25         36
          49         64         81        100        121        144
         169        196        225        256        289        324
         361        400        441        484        529        576
         625        676        729        784        841        900]
 [      3364       2304       1156        729       1600       3364
        1444       1764        900        900       1849       3025
        3481       1849        484       1681        441       1849
        2401       3249        441       1600       2704        961
        1681       1936       2116       2209       1225       1156]
 [1615155721 3494937924 5741547529 8800316100 1755526201 9386896996
  1702965289 5119545601 8222862400 2641343236 1897125136 1926332100
  6659539236 5004147600 2970468004 3816397729 2563093129 2380659264
  6942722329 6892486441 2345755489 6889166001 2602632256 4082826609
  1815782544 9253093249 9743071849 9098679769 

 - Filtrar funcionários com salários maiores que 60.000


In [57]:
indices = np.where(dataset[:, 2] > 60000)
salaries_over_60000 = dataset[indices]
print(salaries_over_60000)

[[    3    34 75773    14]
 [    4    27 93810    17]
 [    6    58 96886     2]
 [    8    42 71551     4]
 [    9    30 90680    29]
 [   13    59 81606    10]
 [   14    43 70740    14]
 [   16    41 61777    15]
 [   19    49 83323    23]
 [   20    57 83021    21]
 [   22    40 83001    18]
 [   24    31 63897    26]
 [   26    44 96193    29]
 [   27    46 98707    15]
 [   28    47 95387     1]
 [   29    35 94638    25]
 [   30    34 63483     7]]


 - Ordenar o dataset pelo salário


In [58]:
sorted_indices = np.argsort(dataset[:, 2])
sorted_dataset = dataset[sorted_indices]
print(sorted_dataset)

[[    1    58 40189     7]
 [    7    38 41267     6]
 [    5    40 41899     4]
 [   25    41 42612    25]
 [   11    43 43556    26]
 [   12    55 43890    34]
 [   21    21 48433    16]
 [   18    43 48792    14]
 [   17    21 50627     8]
 [   23    52 51016    24]
 [   10    30 51394    18]
 [   15    22 54502    31]
 [    2    48 59118     8]
 [   16    41 61777    15]
 [   30    34 63483     7]
 [   24    31 63897    26]
 [   14    43 70740    14]
 [    8    42 71551     4]
 [    3    34 75773    14]
 [   13    59 81606    10]
 [   22    40 83001    18]
 [   20    57 83021    21]
 [   19    49 83323    23]
 [    9    30 90680    29]
 [    4    27 93810    17]
 [   29    35 94638    25]
 [   28    47 95387     1]
 [   26    44 96193    29]
 [    6    58 96886     2]
 [   27    46 98707    15]]


 - Criar uma cópia do dataset

In [59]:
dataset_copy = dataset.copy()
print(dataset_copy)

[[    1    58 40189     7]
 [    2    48 59118     8]
 [    3    34 75773    14]
 [    4    27 93810    17]
 [    5    40 41899     4]
 [    6    58 96886     2]
 [    7    38 41267     6]
 [    8    42 71551     4]
 [    9    30 90680    29]
 [   10    30 51394    18]
 [   11    43 43556    26]
 [   12    55 43890    34]
 [   13    59 81606    10]
 [   14    43 70740    14]
 [   15    22 54502    31]
 [   16    41 61777    15]
 [   17    21 50627     8]
 [   18    43 48792    14]
 [   19    49 83323    23]
 [   20    57 83021    21]
 [   21    21 48433    16]
 [   22    40 83001    18]
 [   23    52 51016    24]
 [   24    31 63897    26]
 [   25    41 42612    25]
 [   26    44 96193    29]
 [   27    46 98707    15]
 [   28    47 95387     1]
 [   29    35 94638    25]
 [   30    34 63483     7]]
